// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {servermanager} from '../models';
import {downloader} from '../models';
import {utils} from '../models';

export function AddContent(arg1:string,arg2:string,arg3:string):Promise<servermanager.ContentItem>;

export function ApplyModpack(arg1:string,arg2:string):Promise<servermanager.ModpackMeta>;

export function BrowseCurseForge(arg1:number,arg2:string,arg3:string):Promise<Array<downloader.CurseForgeSearchResult>>;

export function BrowseForJar():Promise<string>;

export function BrowseForModpackZip():Promise<string>;

export function BrowseForServerDir():Promise<string>;

export function BrowseHangar():Promise<Array<downloader.HangarSearchResult>>;

export function BrowseModrinth(arg1:string,arg2:string,arg3:string):Promise<Array<downloader.ModrinthSearchResult>>;

export function BrowseSpiget():Promise<Array<downloader.SpigetSearchResult>>;

export function CreateServer(arg1:servermanager.CreateServerPayload):Promise<servermanager.ServerInstance>;

export function DeleteServer(arg1:string):Promise<void>;

export function DetectJava():Promise<Array<utils.JavaInstall>>;

export function GetAppSettings():Promise<utils.AppSettings>;

export function GetAvailableVersions():Promise<Record<string, Array<string>>>;

export function GetConsoleLogs(arg1:string):Promise<Array<string>>;

export function GetServerProperties(arg1:string):Promise<string>;

export function GetServerResources(arg1:string):Promise<Record<string, any>>;

export function ImportServer(arg1:servermanager.ImportServerPayload):Promise<servermanager.ServerInstance>;

export function InstallCurseForgeFile(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<servermanager.ContentItem>;

export function InstallHangarPlugin(arg1:string,arg2:string,arg3:string):Promise<servermanager.ContentItem>;

export function InstallModrinthMod(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<servermanager.ContentItem>;

export function InstallSpigetPlugin(arg1:string,arg2:number):Promise<servermanager.ContentItem>;

export function ListContent(arg1:string,arg2:string):Promise<Array<servermanager.ContentItem>>;

export function ListServers():Promise<Array<servermanager.ServerInstance>>;

export function RemoveContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartServer(arg1:string):Promise<void>;

export function SaveAppSettings(arg1:utils.AppSettings):Promise<void>;

export function SearchCurseForge(arg1:string,arg2:number,arg3:string,arg4:string):Promise<Array<downloader.CurseForgeSearchResult>>;

export function SearchHangar(arg1:string):Promise<Array<downloader.HangarSearchResult>>;

export function SearchModrinth(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<downloader.ModrinthSearchResult>>;

export function SearchSpiget(arg1:string):Promise<Array<downloader.SpigetSearchResult>>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function StartServer(arg1:string):Promise<string>;

export function StopServer(arg1:string):Promise<string>;

export function SubscribeConsole(arg1:string):Promise<void>;

export function ToggleContent(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function UnsubscribeConsole(arg1:string):Promise<void>;

export function UpdateServerConfig(arg1:servermanager.UpdateConfigPayload):Promise<void>;

export function ValidateCurseForgeKey(arg1:string):Promise<void>;
