// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DetectJava() {
  return window['go']['main']['App']['DetectJava']();
}

export function GetAvailableVersions() {
  return window['go']['main']['App']['GetAvailableVersions']();
}

export function GetConsoleLogs(arg1) {
  return window['go']['main']['App']['GetConsoleLogs'](arg1);
}

export function GetServerProperties(arg1) {
  return window['go']['main']['App']['GetServerProperties'](arg1);
}

export function GetServerResources(arg1) {
  return window['go']['main']['App']['GetServerResources'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function SubscribeConsole(arg1) {
  return window['go']['main']['App']['SubscribeConsole'](arg1);
}

export function UnsubscribeConsole(arg1) {
  return window['go']['main']['App']['UnsubscribeConsole'](arg1);
}

export function UpdateServerConfig(arg1) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1);
}
