// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {servermanager} from '../models';
import {utils} from '../models';

export function CreateServer(arg1:servermanager.CreateServerPayload):Promise<servermanager.ServerInstance>;

export function DeleteServer(arg1:string):Promise<void>;

export function DetectJava():Promise<Array<utils.JavaInstall>>;

export function GetAvailableVersions():Promise<Record<string, Array<string>>>;

export function GetConsoleLogs(arg1:string):Promise<Array<string>>;

export function GetServerProperties(arg1:string):Promise<string>;

export function GetServerResources(arg1:string):Promise<Record<string, any>>;

export function ListServers():Promise<Array<servermanager.ServerInstance>>;

export function RestartServer(arg1:string):Promise<void>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function StartServer(arg1:string):Promise<string>;

export function StopServer(arg1:string):Promise<string>;

export function SubscribeConsole(arg1:string):Promise<void>;

export function UnsubscribeConsole(arg1:string):Promise<void>;

export function UpdateServerConfig(arg1:servermanager.UpdateConfigPayload):Promise<void>;
