// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddContent'](arg1, arg2, arg3);
}

export function ApplyModpack(arg1, arg2) {
  return window['go']['main']['App']['ApplyModpack'](arg1, arg2);
}

export function BrowseCurseForge(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowseCurseForge'](arg1, arg2, arg3);
}

export function BrowseForBackupDir() {
  return window['go']['main']['App']['BrowseForBackupDir']();
}

export function BrowseForJar() {
  return window['go']['main']['App']['BrowseForJar']();
}

export function BrowseForModpackZip() {
  return window['go']['main']['App']['BrowseForModpackZip']();
}

export function BrowseForServerDir() {
  return window['go']['main']['App']['BrowseForServerDir']();
}

export function BrowseHangar() {
  return window['go']['main']['App']['BrowseHangar']();
}

export function BrowseModrinth(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowseModrinth'](arg1, arg2, arg3);
}

export function BrowseSpiget() {
  return window['go']['main']['App']['BrowseSpiget']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteBackup(arg1, arg2) {
  return window['go']['main']['App']['DeleteBackup'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DetectJava() {
  return window['go']['main']['App']['DetectJava']();
}

export function GetActivePlayers(arg1) {
  return window['go']['main']['App']['GetActivePlayers'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetAvailableVersions() {
  return window['go']['main']['App']['GetAvailableVersions']();
}

export function GetConsoleLogs(arg1) {
  return window['go']['main']['App']['GetConsoleLogs'](arg1);
}

export function GetPlayerRoles(arg1) {
  return window['go']['main']['App']['GetPlayerRoles'](arg1);
}

export function GetServerProperties(arg1) {
  return window['go']['main']['App']['GetServerProperties'](arg1);
}

export function GetServerResources(arg1) {
  return window['go']['main']['App']['GetServerResources'](arg1);
}

export function ImportServer(arg1) {
  return window['go']['main']['App']['ImportServer'](arg1);
}

export function InstallCurseForgeFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InstallCurseForgeFile'](arg1, arg2, arg3, arg4, arg5);
}

export function InstallHangarPlugin(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallHangarPlugin'](arg1, arg2, arg3);
}

export function InstallModrinthMod(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InstallModrinthMod'](arg1, arg2, arg3, arg4, arg5);
}

export function InstallSpigetPlugin(arg1, arg2) {
  return window['go']['main']['App']['InstallSpigetPlugin'](arg1, arg2);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListContent(arg1, arg2) {
  return window['go']['main']['App']['ListContent'](arg1, arg2);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function RemoveContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveContent'](arg1, arg2, arg3);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SearchCurseForge(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchCurseForge'](arg1, arg2, arg3, arg4);
}

export function SearchHangar(arg1) {
  return window['go']['main']['App']['SearchHangar'](arg1);
}

export function SearchModrinth(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchModrinth'](arg1, arg2, arg3, arg4);
}

export function SearchSpiget(arg1) {
  return window['go']['main']['App']['SearchSpiget'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function SubscribeConsole(arg1) {
  return window['go']['main']['App']['SubscribeConsole'](arg1);
}

export function ToggleContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ToggleContent'](arg1, arg2, arg3, arg4);
}

export function UnsubscribeConsole(arg1) {
  return window['go']['main']['App']['UnsubscribeConsole'](arg1);
}

export function UpdateServerConfig(arg1) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1);
}

export function ValidateCurseForgeKey(arg1) {
  return window['go']['main']['App']['ValidateCurseForgeKey'](arg1);
}
